[package]
name = "twitch_eventsub"
version = "0.1.1"
edition = "2021"
description = "A library that handles everything with Twitch EventSub helix api for you."
repository = "https://github.com/lilith645/TwitchEventSub-rs.git"
authors = ["Owlkaline"]
categories = [
  "api-bindings",
  "web-programming::websocket",
  "authentication",
  "network-programming",
]
keywords = ["Twitch", "EventSub", "oauth", "api", "websocket"]
resolver = "2"
license = "MIT"
exclude = ["examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
only_raw_responses = []
#godot = ["dep:godot"]

[dependencies]
websocket = { version = "0.27.1", default-features = false, features = [
  "sync",
  "sync-ssl",
] }
enum_all_variants = "0.2.0"
curl = "0.4.46"
#sysinfo = "0.30.12"
open = "5.1.4"
simple_env_load = "0.2.0"
simple-logging = "2.0.2"
log = "0.4"
#twitch_eventsub_structs = { path = "../TwitchEventSubStructs" }
twitch_eventsub_structs = { git = "https://github.com/Owlkaline/TwitchEventSubStructs.git" }
