[package]
name = "twitch_eventsub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.27.1"
enum_all_variants = "0.2.0"
serde_json = "1.0.117"
serde = "1.0.117"
serde_derive = "1.0.117"
curl = "0.4.46"
sysinfo = "0.30.12"
open = "5.1.4"
simple_env_load = "*"
