[package]
name = "rust_project"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.1.1"
twitch_eventsub = { path = "../../../Git/TwitchEventSub-rs/", features=["godot"] }
#twitch_eventsub = { git = "https://github.com/lilith645/TwitchEventSub-rs.git" }
